name: process
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  horizontal_data_table: ^4.1.5
  data_table_2: ^2.4.2
  infinite_scroll_pagination: ^3.2.0
  http: ^0.13.6
  flutter_breadcrumb: ^1.0.1
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  image_picker: ^0.8.6
  file_picker: ^5.2.1
  page_transition: ^2.0.9
  lottie: ^1.4.3
  get: ^4.6.5
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  table_calendar: ^3.0.8
  date_format: ^2.0.7
  day_night_time_picker: ^1.1.3
  pdf: ^3.8.4
  printing: ^5.9.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  #expansion_tile_card: ^2.0.0
  quickalert: ^1.0.1
  connectivity_plus: ^3.0.3
  cron: ^0.5.1
  dio: ^5.1.2
  permission_handler: ^10.2.1
  mask_text_input_formatter: ^2.4.0
  external_path: ^1.0.3
  flutter_image_compress: ^2.0.1
  modal_progress_hud_nsn: ^0.3.0
  rename: ^2.1.1
  vibration: ^1.7.7
  upgrader: ^6.5.0
  animated_splash_screen: ^1.3.0
  dotted_line: ^3.2.2
  package_info_plus: ^4.1.0
  #flutter_face_api_beta: ^0.0.78

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
